/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SystemEventEntry service. Represents a row in the &quot;SystemEventEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.SystemEventEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.SystemEventEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SystemEventEntry
 * @see com.liferay.portal.model.impl.SystemEventEntryImpl
 * @see com.liferay.portal.model.impl.SystemEventEntryModelImpl
 * @generated
 */
public interface SystemEventEntryModel extends AttachedModel,
	BaseModel<SystemEventEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a system event entry model instance should use the {@link SystemEventEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this system event entry.
	 *
	 * @return the primary key of this system event entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this system event entry.
	 *
	 * @param primaryKey the primary key of this system event entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the system event ID of this system event entry.
	 *
	 * @return the system event ID of this system event entry
	 */
	public long getSystemEventId();

	/**
	 * Sets the system event ID of this system event entry.
	 *
	 * @param systemEventId the system event ID of this system event entry
	 */
	public void setSystemEventId(long systemEventId);

	/**
	 * Returns the group ID of this system event entry.
	 *
	 * @return the group ID of this system event entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this system event entry.
	 *
	 * @param groupId the group ID of this system event entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this system event entry.
	 *
	 * @return the company ID of this system event entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this system event entry.
	 *
	 * @param companyId the company ID of this system event entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this system event entry.
	 *
	 * @return the user ID of this system event entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this system event entry.
	 *
	 * @param userId the user ID of this system event entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this system event entry.
	 *
	 * @return the user uuid of this system event entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this system event entry.
	 *
	 * @param userUuid the user uuid of this system event entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this system event entry.
	 *
	 * @return the user name of this system event entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this system event entry.
	 *
	 * @param userName the user name of this system event entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this system event entry.
	 *
	 * @return the create date of this system event entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this system event entry.
	 *
	 * @param createDate the create date of this system event entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the event type of this system event entry.
	 *
	 * @return the event type of this system event entry
	 */
	public int getEventType();

	/**
	 * Sets the event type of this system event entry.
	 *
	 * @param eventType the event type of this system event entry
	 */
	public void setEventType(int eventType);

	/**
	 * Returns the fully qualified class name of this system event entry.
	 *
	 * @return the fully qualified class name of this system event entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this system event entry.
	 *
	 * @return the class name ID of this system event entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this system event entry.
	 *
	 * @param classNameId the class name ID of this system event entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this system event entry.
	 *
	 * @return the class p k of this system event entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this system event entry.
	 *
	 * @param classPK the class p k of this system event entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the class uuid of this system event entry.
	 *
	 * @return the class uuid of this system event entry
	 */
	@AutoEscape
	public String getClassUuid();

	/**
	 * Sets the class uuid of this system event entry.
	 *
	 * @param classUuid the class uuid of this system event entry
	 */
	public void setClassUuid(String classUuid);

	/**
	 * Returns the event set of this system event entry.
	 *
	 * @return the event set of this system event entry
	 */
	@AutoEscape
	public String getEventSet();

	/**
	 * Sets the event set of this system event entry.
	 *
	 * @param eventSet the event set of this system event entry
	 */
	public void setEventSet(String eventSet);

	/**
	 * Returns the event ID of this system event entry.
	 *
	 * @return the event ID of this system event entry
	 */
	@AutoEscape
	public String getEventId();

	/**
	 * Sets the event ID of this system event entry.
	 *
	 * @param eventId the event ID of this system event entry
	 */
	public void setEventId(String eventId);

	/**
	 * Returns the parent event ID of this system event entry.
	 *
	 * @return the parent event ID of this system event entry
	 */
	@AutoEscape
	public String getParentEventId();

	/**
	 * Sets the parent event ID of this system event entry.
	 *
	 * @param parentEventId the parent event ID of this system event entry
	 */
	public void setParentEventId(String parentEventId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SystemEventEntry systemEventEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SystemEventEntry> toCacheModel();

	@Override
	public SystemEventEntry toEscapedModel();

	@Override
	public SystemEventEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}